{
 "title": "Energy",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Name", "query": { "query": "energy_watthour" } }
  ]
 },
 "panels": [
  {
   "title": "Verbrauch pro Stunde",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_watthour{name!=\"Stromverbrauch Gesamt\"} - (energy_watthour{name!=\"Stromverbrauch Gesamt\"} offset 1h) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Verbrauch pro Tag",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_watthour{name!=\"Stromverbrauch Gesamt\"} - (energy_watthour{name!=\"Stromverbrauch Gesamt\"} offset 1d) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_watthour{name=\"Stromverbrauch Gesamt\"}"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_watthour_rate * 3600 > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Verbrauch im Zeitraum",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "energy_watthour - (energy_watthour @ start()) > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Aktueller Verbrauch (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "energy_watthour{name!=\"Stromverbrauch Gesamt\"} - (energy_watthour{name!=\"Stromverbrauch Gesamt\"} @ start()) > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "energy_watthour{name=\"Stromverbrauch Gesamt\"} - (energy_watthour{name=\"Stromverbrauch Gesamt\"} @ start()) > 0",
     "legendFormat": "Gesamt"
    }
   ]
  },
  {
   "title": "Aktueller Verbrauch $Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "repeat": "Name",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum_over_time(energy_watthour_rate{name=~\"$Name\"}[30m]) * 2 * 60",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}